### PR TITLE
Docker integration using Github CI Actions

### PR DESCRIPTION
**Pull request by initd1**
Docker integration using Github CI Actions

### CODE REVIEW

**Comment by initd1** [comment]
CI/CD for docker integration completed and working. 

Docker image built, and pushed successfully to dockerhub as evidenced by the checks on this PR. 

Latest image in Dockerhub repository https://hub.docker.com/r/initd1/hackalert:

image

> ❕  **Future**: 
>  Potentially change the tag of the image being pushed to follow Semantic Versioning standard

**Review by GH-Syn — COMMENTED** [review]
I think changing it to something like CI or Docker Integration might be a better name. thoughts?

**Comment by initd1** [comment]
> I think changing it to something like CI or Docker Integration might be a better name. thoughts?

Do you mean changing the name of the Github Action to Docker integration? or the docker image tag?

**Comment by GH-Syn** [comment]
I was referring to the name of the GitHub action, as I thought that it might be more comprehensive.

**Comment by initd1** [comment]
I agree..I will change it to Docker integration

**Pull request merged**
