### PR TITLE
add unit tests and additional necessary omissions

### PR DESCRIPTION
**Pull request by GH-Syn**
- feat: Added a unit test for `BreachChecker` method: `is_valid_email`
 - style: Decorators for `BreachChecker`
 - ref: regex statement to include additional syntax:
    
    ```python
    regex = '^[a-z0-9]+[\._]?[a-z0-9]+[@]\w+[.]\w{2,3}$'  
    ```
    > source: https://www.c-sharpcorner.com/article/how-to-validate-an-email-address-in-python/

### CODE REVIEW

**Comment by GH-Syn** [comment]
- I'm not sure if you'd want the modified `is_valid_email` function in `BreachCherker` to be moved to the `Validator` class, as I noticed they were duplicated?

**Comment by GH-Syn** [comment]
## Changes
 - [linting with pythons black code linter](https://github.com/psf/black)
 - Refactoring of `test_branch_checker.py` due to duplicated code
 - logging implementation with logs (still need to add logs to `.gitignore` 
   > **Note**: Logging is still a WIP

**Comment by GH-Syn** [comment]
## TODO:
 - [ ] Global refactor to implement changes from [994b210](https://github.com/initd1/Cyber-Breach-Detector/pull/20/commits/994b210f0a379ff65a036d41720f51599745f58f) and [ea9e638](https://github.com/initd1/Cyber-Breach-Detector/pull/20/commits/ea9e6381e286594df32fb4b6f3ef5c6b283ae275)
 - [ ] Unit tests for other files

**Comment by initd1** [comment]
> ## Changes
> * [linting with pythons black code linter](https://github.com/psf/black)
> * Refactoring of `test_branch_checker.py` due to duplicated code
> * logging implementation with logs (still need to add logs to `.gitignore`
> 
> > Note: Logging is still a WIP however colors _are_ supported as well as files.

@GH-Syn Linting work and logging implementation looks good. thanks for contributing. Please clarify on the removal of classes..

**Comment by GH-Syn** [comment]
> Please clarify on the removal of classes.

@initd1 Sure, absolutely.

 - I noticed that (some of) the code in [`Common/breach_checker.py`](https://github.com/initd1/Cyber-Breach-Detector/blob/main/Common/breach_checker.py) and [`Common/utils.py`](https://github.com/initd1/Cyber-Breach-Detector/blob/main/Common/utils.py) were identical.
https://github.com/initd1/Cyber-Breach-Detector/blob/3bcb77a6289128054565827be84995ab2b8b5963/Common/utils.py#L24-L40
https://github.com/initd1/Cyber-Breach-Detector/blob/3bcb77a6289128054565827be84995ab2b8b5963/Common/breach_checker.py#L7-L23
 - I'd also like to point out that when these changes are made, I also converted methods that do not need to be in classes into functions.

**Comment by GH-Syn** [comment]
### Regarding documentation strings
 - Currently using a modified version of what's found in the requests library. Example from `requests/api.py`:

```python
def options(url, **kwargs):
    r"""Sends an OPTIONS request.

    :param url: URL for the new :class:`Request` object.
    :param \*\*kwargs: Optional arguments that ``request`` takes.
    :return: :class:`Response <Response>` object
    :rtype: requests.Response
    """

    return request("options", url, **kwargs)
```
> https://github.com/psf/requests/blob/7f694b79e114c06fac5ec06019cada5a61e5570f/requests/api.py#L76-L85


> **Note** For some reason the link is not automatically embedding :frowning_face:

**Comment by GH-Syn** [comment]
## Regarding Testing
 > **Warning** Integration testing and (some) unit tests can't be done if they require an api key. This must be done off the books unfortunately.

**Comment by GH-Syn** [comment]
## Current tasks
 - [ ] Move methods that can be converted to functions in `ip_reputation_checker.py`
 - [ ] Fix up comments, adding comments where needed and omitting redundant ones.

**Pull request closed without merging**
